general {
    # Dejamos la sección general vacía o mínima.
    # En escritorio, no necesitamos ganchos complejos si solo queremos apagar la pantalla.
    ignore_dbus_inhibit = false
}

# --- REGLA ÚNICA: Gestión de Monitor (10 min) ---
listener {
    timeout = 600                            # 10 minutos (600 segundos)
    on-timeout = hyprctl dispatch dpms off   # Apagar la señal de video
    on-resume = hyprctl dispatch dpms on     # Encender inmediatamente al detectar actividad
}
